### PR TITLE
Started port to godot 4.1

### PR DESCRIPTION
**Pull request by Reisyukaku**
Everything compiles and runs, but there is still some bugs to work out.

Known issues:
- Impulse vector seems wonky; not applying force in the right directions sometimes
- Planet shaders still need fixing (mostly lighting?)
- Collisions still broken

### CODE REVIEW

**Comment by Hoimar** [comment]
Hey there, thanks so much for the PR, hugely appreciated.
I'll take a look at your work and see if the bugs look familiar or if they are 4.0 specific.
I'll get back to you ASAP.

With the rewrite of the `PhysicsServer`, I expect more stability in parallelized collision shape generation.

Perhaps we'll just disable collisions for now, then branch off the current dev branch into a 3.x branch and merge your branch with disabled collisions into dev.

**Comment by Reisyukaku** [comment]
fixed the atmosphere shader issue and tested on 4.1.
Main takeaway is quad-mesh flipface = true in atmosphere gdscript, and line 103 in the shader.

**Comment by Hoimar** [comment]
Thanks, looking good.

Could you please make sure to use the .gitignore with Godot presets? It looks like you missed that file and now git added all the usually ignored godot files to the commit.

Please update and push your commit again so I can check out the changes.

**Comment by Hoimar** [comment]
Okay this is looking good, I'll squash the commits together and merge.
Thanks so much for the contribution!

**Pull request merged**
